site_name: "Run Away"
theme:
  name: material
  language: pt
  features:
    - navigation.instant
  palette:
    primary: purple
    accent: purple

extra_css:
  - stylesheets/extra.css

nav:
  - In√≠cio: index.md
  - Ambiete de desenvolvimento: ambiente.md
