site_name: "Run Away"
theme:
  name: material
  language: pt
  features:
    - navigation.instant
  palette:
    primary: purple
    accent: purple

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

nav:
  - Início: index.md
  - Ambiete de desenvolvimento: ambiente.md
  - Algoritmo gerador de árvore: gerador.md
